### ISSUE TITLE
Update org.gnome.Platform - EoL

### ISSUE THREAD

**Issue by ivyturner** [flathub/com.github.bleakgrey.tootle#18]
org.gnome.Platform branch 40 is now End-of-Life and needs to be updated :)

**Comment by ghost** [comment]
I think that is important update the runtime of flatpak version because the runtime of GNOME 40 isn't supported since 21,March of 2022 also I think that update the runtime and the visual appearance with the last changes of GNOME, it will make that the application looks good.In this time, please update the runtime for the version 42

**Comment by hfiguiere** [comment]
#21 is a step forward though.

**Comment by hfiguiere** [comment]
it doesn't build as is on GNOME 42

**Comment by cagatay-y** [comment]
Solved with #22
